Repository stleary/JSON-java, pull requests merged in 2023-10, with the labels that each got.

#776 JUnit 4.13.2
  build.gradle
  pom.xml
Labels: hacktoberfest-accepted

#774 Removing excessive synchronization
  src/main/java/org/json/JSONArray.java
  src/main/java/org/json/JSONObject.java
Labels: hacktoberfest-accepted

#782 Fix XMLTest.testIndentComplicatedJsonObjectWithArrayAndWithConfig() for Windows - in the test
  src/test/java/org/json/junit/XMLTest.java
Labels: hacktoberfest-accepted

#778 Fix XMLTest.testIndentComplicatedJsonObjectWithArrayAndWithConfig() for Windows - in the test
  src/test/java/org/json/junit/XMLTest.java
Labels: hacktoberfest-accepted

#779 add validity check for JSONObject constructors
  src/main/java/org/json/JSONObject.java
  src/test/java/org/json/junit/JSONObjectTest.java
  src/test/java/org/json/junit/data/GenericBean.java
Labels: hacktoberfest-accepted

#783 optLong vs getLong inconsistencies
  src/main/java/org/json/JSONObject.java
  src/test/java/org/json/junit/JSONObjectDecimalTest.java
  src/test/java/org/json/junit/JSONObjectNumberTest.java
  src/test/java/org/json/junit/JSONObjectTest.java
  src/test/java/org/json/junit/JsonNumberZeroTest.java
Labels: hacktoberfest-accepted

#788 Fix string compare unit tests
  src/test/java/org/json/junit/JSONMLTest.java
  src/test/java/org/json/junit/JSONObjectTest.java
Labels: Approved - 3-day window, hacktoberfest-accepted

#798 fix: flakiness in org.json.junit.XMLTest#testIndentComplicatedJsonObjectWithArrayAndWithConfig
  src/test/java/org/json/junit/XMLTest.java
Labels: Approved - 3-day window, hacktoberfest-accepted

#801 Updates the pipeline to validate that packaging a jar works properly
  .github/workflows/pipeline.yml
  .gitignore
  README.md
  pom.xml
Labels: Approved - 3-day window, hacktoberfest-accepted

#794 XML optLong/getLong equivalent updates for string to number conversion.
  src/main/java/org/json/XML.java
  src/test/java/org/json/junit/JSONMLTest.java
  src/test/java/org/json/junit/XMLConfigurationTest.java
  src/test/java/org/json/junit/XMLTest.java
Labels: Hacktoberfest

#812 docs: use syntax highlighting
  README.md
Labels: Hacktoberfest

#820 Close XML tag explicitly for empty tags with configuration.
  src/main/java/org/json/XML.java
  src/main/java/org/json/XMLParserConfiguration.java
  src/test/java/org/json/junit/XMLConfigurationTest.java
  src/test/java/org/json/junit/XMLTest.java
Labels: hacktoberfest-accepted

#814 Refactor duplicate code for stringToNumber() in JSONObject, JSONArray, and XML
  src/main/java/org/json/JSONArray.java
  src/main/java/org/json/JSONObject.java
  src/main/java/org/json/NumberConversionUtil.java
  src/main/java/org/json/XML.java
  src/test/java/org/json/NumberConversionUtilTest.java
Labels: hacktoberfest-accepted
