Repository stleary/JSON-java, pull requests merged in 2024-11, with the labels that each got.

#911 Revert strict mode
  src/main/java/org/json/JSONArray.java
  src/main/java/org/json/JSONObject.java
  src/main/java/org/json/JSONParserConfiguration.java
  src/main/java/org/json/JSONTokener.java
  src/test/java/org/json/junit/CDLTest.java
  src/test/java/org/json/junit/JSONArrayTest.java
  src/test/java/org/json/junit/JSONMLTest.java
  src/test/java/org/json/junit/JSONObjectNumberTest.java
  src/test/java/org/json/junit/JSONObjectTest.java
  src/test/java/org/json/junit/JSONParserConfigurationTest.java
  src/test/java/org/json/junit/XMLConfigurationTest.java
  src/test/java/org/json/junit/XMLTest.java
  src/test/resources/JSONArrayExpectedTestCaseForToJsonArrayTest.json
  src/test/resources/XmlTestCaseTestToJsonArray.xml
  src/test/resources/compliantJsonArray.json
Labels: Approved - 7 day comment window

#894 update-jsonpath: update jsonpath from 2.4.0 to 2.9.0
  build.gradle
  pom.xml
Labels: Approved - by myself, Approved - 7 day comment window

#907 Fix a bug when calling JSONArray.addAll() with Collection as Object
  src/main/java/org/json/JSONArray.java
  src/test/java/org/json/junit/JSONArrayTest.java
Labels: Approved - 3-day window
